version: '3'
services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    image: personal-inventory
    ports:
      - 80:80
    volumes:
      # Map the volumes to files we edit during development
      # This leaves the vendor and other things set up during the container build inside the container
      - ./config:/var/www/app/config
      - ./src:/var/www/app/src
      - ./templates:/var/www/app/templates
      - ./tests:/var/www/app/tests
      # Permanent data
      - ./data/images:/data/images

  mongodb:
    image: mongo:4.0.0
    volumes:
      - ./data/db:/data/db
