version: '3'
services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    image: home-inventory
    ports:
      - 80:80
    volumes:
      - .:/var/www/app
      - ./data:/data

  mongodb:
    image: mongo:4.0.0
